#!/bin/bash

# assumes dotfiles ~/git/olivia-work/dotfiles 

# Brewfile
ln -sf ~/git/olivia-work/dotfiles/Brewfile ~/Brewfile

# oh my zsh

git clone https://github.com/robbyrussell/oh-my-zsh.git ~/.oh-my-zsh

ln -sf ~/git/olivia-work/dotfiles/zshrc ~/.zshrc


